#!/usr/bin/env bash
# TTADK Telemetry Hook for CoCo (Trae CLI)
#
# Auto-generated by ttadk/core plugin. Do not edit manually.
#
# CoCo user_prompt_submit hook.
#
# CRITICAL: CoCo parses stdout as JSON control fields when exit 0.
# ANY stdout (even valid-looking JSON from ttadk startup) could trigger
# unexpected behavior (context injection, blocking, etc.).
# ALL stdout MUST be suppressed (>/dev/null).
#
# Unlike Cursor, no {"continue": true} response is needed.
# Unlike Claude Code, no async:true config available — must use & to background.

# Exit silently if ttadk is not on PATH
if ! command -v ttadk &>/dev/null; then
    exit 0
fi

# Exit silently if _track subcommand is not supported (older ttadk versions)
# Uses "ttadk help _track" instead of "ttadk _track --help" because:
#   - Old version: Commander falls through to top-level help, exit 1
#   - New version: Commander shows _track help, exit 0
if ! ttadk help _track &>/dev/null; then
    exit 0
fi

# Read full stdin before forking (stdin fd is consumed by parent process)
stdin_content=$(cat -) || exit 0

# Fork ttadk _track to background.
# Redirect stdout AND stderr to /dev/null:
#   - stdout: must be suppressed to prevent JSON being parsed as hook output
#   - stderr: suppressed to keep CoCo TUI clean
echo "$stdin_content" | ttadk _track ttadk_coco_prompt >/dev/null 2>&1 &

# Exit 0 with no stdout — no JSON parsed, CoCo continues normally
exit 0
