ALTER TABLE projects ADD COLUMN text_model TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN image_model TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN video_model TEXT NOT NULL DEFAULT '';
