#!/usr/bin/env bash
# TTADK Telemetry Hook for CodeX
#
# Auto-generated by ttadk/core plugin. Do not edit manually.
#
# Codex UserPromptSubmit hook.
#
# CRITICAL: Codex injects ANY stdout from this script as developer context
# into the current AI turn. ALL stdout MUST be suppressed (>/dev/null).
# stderr is safe to discard but must not reach Codex's TUI either.

# Exit silently if ttadk is not on PATH
if ! command -v ttadk &>/dev/null; then
    exit 0
fi

# Exit silently if _track subcommand is not supported (older ttadk versions)
# Uses "ttadk help _track" instead of "ttadk _track --help" because:
#   - Old version: Commander falls through to top-level help, exit 1
#   - New version: Commander shows _track help, exit 0
if ! ttadk help _track &>/dev/null; then
    exit 0
fi

# Read full stdin before forking (stdin is consumed by parent process)
stdin_content=$(cat -) || exit 0

# Fork ttadk _track to background.
# Redirect stdout AND stderr to /dev/null:
#   - stdout: must be suppressed to prevent context injection into Codex
#   - stderr: suppressed to keep Codex TUI clean
echo "$stdin_content" | ttadk _track ttadk_codex_prompt >/dev/null 2>&1 &

# Exit 0 with no stdout — transparent pass-through to Codex
exit 0
